name: prebet
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #Payment
  payment: ^0.0.1
  flutter_paypal_payment: ^1.0.8

  #Hive - to keep the user login after closing the app
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Location / Map
  google_maps_widget: ^1.0.6

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoo.png"

flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true
  image: "assets/images/logoo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logoo.png
